#!/usr/bin/env python3

import sys
import error
import poll

def main():
    try: 
        sys.argv.index("-h")
    except ValueError:
        exit(poll.start(sys.argv))
    else:
        exit(error.usage())

if __name__ == "__main__":
    main()