#!/usr/bin/env python3

import sys
import error
import unsold

def main():
	try: 
		sys.argv.index("-h")
	except ValueError:
		exit(unsold.start(sys.argv))
	else:
		exit(error.usage())

if __name__ == "__main__":
	main()